version: "3.9"

services:
  backend:
    build: ../
    ports:
      - "8000:8000"
    volumes:
      - ../pipeline_ai:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pipeline
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline
    ports:
      - "5432:5432"
